# Generated by Django 4.2.6 on 2024-03-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=100, verbose_name='Service Title')),
                ('service_logo', models.ImageField(upload_to='services/', verbose_name='Logo')),
                ('service_description', models.TextField(verbose_name='Description')),
                ('service_banner', models.ImageField(upload_to='services/', verbose_name='Banner')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('status', models.CharField(choices=[('visible', 'Visible'), ('not visible', 'Not Visible')], default='not visible', max_length=100, verbose_name='Service Status')),
            ],
        ),
    ]
