# Generated by Django 5.0.6 on 2024-06-28 20:01

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_services_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
