# Generated by Django 4.2.6 on 2023-11-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserType',
            field=models.CharField(choices=[('ADMINISTRATION', 'Administration'), ('MODERATOR', 'Moderator'), ('READER', 'Reader')], default='READER', max_length=100, verbose_name='User Type'),
        ),
    ]
