# Generated by Django 4.2.6 on 2023-11-08 19:04

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avator',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='avator/', verbose_name='User Profile Image'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
