# Generated by Django 4.2.6 on 2023-11-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_usertype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administration',
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserType',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('MODERATOR', 'Moderator'), ('READER', 'Reader')], default='ADMINISTRATOR', max_length=100, verbose_name='User Type'),
        ),
    ]
