# Generated by Django 4.2.6 on 2023-11-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserType',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin'), ('Moderator', 'Moderator')], default='User', max_length=100, verbose_name='User Type'),
        ),
    ]
