# Generated by Django 4.2.6 on 2024-01-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Date of Birth'),
        ),
    ]
