# Generated by Django 4.2.6 on 2023-12-22 19:41

import autoslug.fields
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_main_title', models.CharField(max_length=120, verbose_name='Main Title')),
                ('article_sub_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sub Title')),
                ('article_banner_img', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[600, 620], upload_to='article_banner', verbose_name='Banner Image')),
                ('article_description', ckeditor.fields.RichTextField(verbose_name='Article Description')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='article_main_title', unique=True)),
                ('status', models.CharField(choices=[('archived', 'Archived'), ('published', 'Published')], default='archived', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, verbose_name='Tag Name')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=150, verbose_name='Article section Title')),
                ('section_description', ckeditor.fields.RichTextField(verbose_name='Article Section Description')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='article.tags'),
        ),
    ]
