# Generated by Django 4.2.6 on 2023-12-23 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_alter_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesection',
            name='section_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles', verbose_name='Article Section Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='article_banner', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='article.tags'),
        ),
    ]
