# Generated by Django 4.2.6 on 2024-03-20 19:17

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0005_articlecategory_alter_tags_options_articlecomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.CreateModel(
            name='CommentReplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay_text', models.TextField(max_length=200, verbose_name='Replay')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='replay_text', unique=True)),
                ('replay_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='replay UUID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateField(auto_now=True, verbose_name='Updated')),
                ('replay_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articlecomment')),
                ('replayer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
