# Generated by Django 4.2.6 on 2023-12-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_articlecategory_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
