# Generated by Django 4.2.6 on 2023-12-30 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0006_alter_articlecategory_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=200, verbose_name='Comment')),
                ('comment_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='comment UUID')),
                ('created', models.DateField(auto_now=True, verbose_name='Created')),
                ('comment_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
