# Generated by Django 5.0.6 on 2024-05-27 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_articlecomment_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='comment_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_article', to='article.article'),
        ),
        migrations.AlterField(
            model_name='commentreplay',
            name='replay_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay_comment', to='article.articlecomment'),
        ),
    ]
