# Generated by Django 4.2.6 on 2023-11-06 13:56

import ckeditor_uploader.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID')),
                ('worktitle', models.CharField(max_length=100, verbose_name='Title of the Work')),
                ('worksubtitle', models.CharField(max_length=200, verbose_name='Subtitle of the Work')),
                ('shortdesc', models.TextField(max_length=300, verbose_name='Short Banner Description')),
                ('workbanner', models.ImageField(upload_to='work/', verbose_name='Work Banner Image')),
                ('workdescription', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Describe The Work')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
        ),
    ]
