# Generated by Django 4.2.6 on 2023-11-09 19:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_alter_user_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID')),
                ('worktitle', models.CharField(max_length=100, verbose_name='Title of the Work')),
                ('worksubtitle', models.CharField(max_length=200, verbose_name='Subtitle of the Work')),
                ('shortdesc', models.TextField(max_length=280, verbose_name='Short Banner Description')),
                ('workbanner', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[600, 600], upload_to='work/', verbose_name='Work Banner Image')),
                ('workdescription', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Describe The Work')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeQuote', models.TextField(max_length=150, verbose_name='Write Your Quote in short')),
                ('employeeUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee', verbose_name='Employee User')),
            ],
        ),
    ]
