# Generated by Django 4.2.6 on 2023-11-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0002_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='employeeQuote',
            field=models.TextField(max_length=150, verbose_name='Write Your Quote in short'),
        ),
    ]
