# Generated by Django 4.2.6 on 2023-11-07 15:01

import ckeditor.fields
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0002_alter_ourwork_workdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourwork',
            name='workbanner',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[600, 600], upload_to='work/', verbose_name='Work Banner Image'),
        ),
        migrations.AlterField(
            model_name='ourwork',
            name='workdescription',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Describe The Work'),
        ),
    ]
