# Generated by Django 4.2.6 on 2023-11-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='messagetype',
            field=models.CharField(choices=[('READ', 'Read'), ('UNREAD', 'Unread'), ('DONE', 'Done')], default='UNREAD', max_length=50, verbose_name='Message Type'),
        ),
    ]
