# Generated by Django 4.2.6 on 2024-01-09 18:08

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150, verbose_name='Question')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Article Description')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='question', unique=True)),
                ('type_check', models.CharField(choices=[('SHOW', 'Show'), ('HIDE', 'Hide')], default='HIDE', max_length=50, verbose_name='Check Type')),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[1300, 600], upload_to='slider/', verbose_name='Slider Image'),
        ),
    ]
