# Generated by Django 5.0.6 on 2024-05-27 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_faq_alter_slider_slider_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
    ]
