# Generated by Django 5.0.6 on 2024-07-25 18:30

import django.core.validators
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_faq_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTypeBreadCrumbCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bread_crumb_page_type', models.CharField(max_length=150, verbose_name='Bread Crumb Page Type')),
            ],
            options={
                'verbose_name': 'BreadCrumb Category',
                'verbose_name_plural': 'BreadCrumb Categorys',
            },
        ),
        migrations.CreateModel(
            name='BreadCrumb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumb_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], default='IMAGE', max_length=25, verbose_name='BreadCrumb Type')),
                ('breadcrumb_image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1300, 600], upload_to='breadcrumb_images/', verbose_name='BreadCrumb Image')),
                ('breadcrumb_video', models.FileField(blank=True, null=True, upload_to='breadcrumb_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv'])], verbose_name='BreadCrumb Video')),
                ('title', models.CharField(max_length=100, verbose_name='Breadcrumb Title')),
                ('description', models.TextField(max_length=300, verbose_name='Breadcrumb Description')),
                ('page_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.pagetypebreadcrumbcategory')),
            ],
            options={
                'verbose_name': 'BreadCrumb',
                'verbose_name_plural': 'BreadCrumbs',
            },
        ),
    ]
