# Generated by Django 5.0.6 on 2024-07-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_faq_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTypeBreadCrumbCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bread_crumb_page_type', models.CharField(max_length=150, verbose_name='Bread Crumb Page Type')),
            ],
            options={
                'verbose_name': 'BreadCrumb Category',
                'verbose_name_plural': 'BreadCrumb Categorys',
            },
        ),
        migrations.CreateModel(
            name='BreadCrumb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumb_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], default='IMAGE', max_length=25, verbose_name='BreadCrumb Type')),
                ('breadcrumb_video', models.FileField(upload_to='breadcrumb_videos/', verbose_name='BreadCrumb Video')),
                ('title', models.CharField(max_length=100, verbose_name='Breadcrumb Title')),
                ('description', models.TextField(max_length=300, verbose_name='Breadcrumb Description')),
                ('page_type', models.ManyToManyField(to='home.pagetypebreadcrumbcategory')),
            ],
        ),
    ]
